- name: Run base setup on jenkins controller
  hosts: all
  become: true
  vars:
    ansible_host_key_checking: False
  tasks:
    - name: Execute base setup script
      ansible.builtin.script: ../base-setup/install-jenkins-controller.sh