version: '3.8'
services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus_server
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms1g -Xmx2g
    restart: unless-stopped
volumes:
  nexus_data: